apiVersion: v1
kind: Template
labels:
  template: iamp-image-builder-template
metadata:
  annotations:
    description: IAMP Image Builder
  name: iamp-image-builder-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  labels:
    app: fis-java-openshift
  metadata:
    name: fis-java-openshift
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations:
          openshift.io/imported-from: 'registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0'
        from:
          kind: DockerImage
          name: 'registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0'
        generation: 2
        importPolicy: {}
        name: '2.0'
        referencePolicy:
          type: Source
      
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  labels:
    app: ${APP_NAME}
  metadata:
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
      
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  labels:
    app: ${APP_NAME}
  metadata:
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'fis-java-openshift:2.0'
      type: Source

parameters:
- description: The application name.
  displayName: Application Name 
  name: APP_NAME
  value: app