apiVersion: v1
kind: Template
labels:
  template: iamp-service-config-dev
metadata:
  annotations:
    description: iamp-service-config-dev
  name: iamp-service-config-dev
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: iamp-service-config
  data:
    application.properties: |-
     ## =========================================================
     ##              DEV
     ## =========================================================
     ##              Server
     ## =========================================================
     server.address=0.0.0.0
     server.port=8080
     #server.servlet.application-display-name=${project.artifactId}
     #server.servlet.path=/
     #server.servlet.context-path=/${service.name}/${service.version}
     
     ## Tomcat-specific server settings.
     #server.tomcat.accept-count=10
     #server.tomcat.max-connections=10
     #server.tomcat.max-threads=5 
     
     ## =========================================================
     ##              Spring Cloud config
     ## =========================================================
     spring.cloud.config.server.git.uri=ssh://git@github.com/RomdhanH/config-repository.git
     spring.cloud.config.server.git.ignoreLocalSshSettings=true
     spring.cloud.config.server.git.hostKey=AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
     spring.cloud.config.server.git.hostKeyAlgorithm=ssh-rsa
     spring.cloud.config.server.git.privateKey=-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEA2q8FUimul770rRnnlut2onUYqimhspTR9ajR/svTX9HDwSH+\nHeqMUw/3DS6DZwNVz6PlMcm3WeIHSo81jM3jBrgYHpuT5a3kBuPOxBYwmKP9NNRs\nQPHc/2Sb2QRFbCOVjpA/TdbuiZ4JKTq22SZEJE8MgpA/hFCJGJigm17sZE0ON5gw\nelxkig/Mr42JlgZ36cOhSjqRLFMuJRqgdc7DcW6et0GiHNrue+jMikKwBkJdnllV\nV0gPHXEtWvsgzlQOl4cpAqjpuVznQk4hCzAJcYD+KvL264dSlcx3wPQTnnn0Dced\np+0ZAoV3ORe1IpuQXHBN+Gnu80rhA5504WKOKu3N9yQk5gU00Dvj+2qtVYrALBYn\nBqCq5rgLhapjlbh1FYE6sEybYu1+2VtRrH8OjQ2z8EtZx2Mv8D2OWknV+po4q+RY\n9nj1wuy1yAZ2qd9V5pxuHLx4pi2uDJ8v6PRemaukblImjFMBl1O1Kh30qtSKKQQg\nnYk6/gS3lOki0u5SpAjsx2fsRtCBFDYSQtav4eqtDCQzPUXctQcXHomyyi0LILXn\njBE1IkKsF/6xebEhqX2RLbR9vTIGiNvPrUfEHjG8VUJ9i0hSsJgilWjYzKNZAl/c\nR584fTlupyIsVeO/CIMq7+ZZ8AZQk4R9ILPS9LR8IlhvPU/7jT5dO8sH0EcCAwEA\nAQKCAgEAnROOPOAXuoO8+AFdafgjtLlrR/6zWLSww0XJ4LzDTVY8x6MFBrQMqzUS\nfXNliz7ICmdtH4AGpRdHqXSIQGU6pv7gxEt3xkhLO++x+wL9UQapv6K9R0DzPrcj\ngpQg0XYV3NsbvWue11aeufCkmgF0fKgTEk1Oclnuv64R3sgmAD2g8qnsWFe5F7oV\nihueMhbfVxff6JN851uwD5K6oyQrGnUcqAEK0rMnDfW/xaf1C+nrmOwN8q2dvcYn\nj+xGOi4CdTDuciymBTEII4Y/EewlPFQtPOhcF/2RgmvlsMEgvnpWpPc29QHHLxpy\n8p1mzD71SJCaUM62hibIzXKp/aJu/m5hbuxssSCvQAsDMgq0D2ARupdX2iRN9ifj\nHeJGDuR7P1Fzl1JZtu4EEvcGkuqRrCzGzq/K90DfDClx2s1xSZHeRPQKNJmuDQo8\nExvMh/I20ef8sNLaNGNREN+Cej9ZSKZ8rmmnzn35fy8EVsuMSDcbiNGm5ERPxYEe\n3fK1wbMzFRJznbCYxS+piBI6Y+Y3OZoyUCC49ltWCWYCYYmN0ZPOs2fCAitUefVa\ngx57iaKVco22AH+XQAWVTwxCMnnkVrd/D/F3SlqVgtw9XYwFAM2ViWQu5rl0dytQ\n8KO2fVbMXorouH9Fzp0lcGWm3yFKRpCjg2cu7CLRJH4aZzdrx7ECggEBAPs3/WJE\nuc2Eb+FF3pWr4RDtX0KWgg/0pZEQcmz0ncoHt9VErmk89k6gL/Z7CUb4KMxAqBEj\nsTmp6UQ3+TW8WY/UXhMWhaxQF+Zgh0eX4xA2lb7M+yt/KOzbAcpt55M48oS5nOMj\nGl6tf/sMTzSBR0K2/VM5DW9D3pURJELUbKMT+f+zgCgJ8Gt5W/BZG/L6Md3io0bm\nslSlh9uOTdcov9G8A5mLW1KzipdzTYP08KpKZj8WgBlqzMSIPkYIHAx7b4j/aOx6\naIl2q4T/mXDSgNzLGKCwDve8BIM776WDX8sYfniBUD0/ijpFxbCcOLZIIJt7c++Z\n0lH0rEGRGT0k6C0CggEBAN7YgsqAuRqoVa7F78VzpZfppeTEywW4fhgVfAnNlm55\ns3Cf7/8kSxnHkMkJAcXp6eG+Ixd+0qcXTIbGdcqKumuH2AjBh2mJeOeAwzAj1TSb\nUXAUARSpWvvnLHVECQE9n+5oGXpKi0EbDzgCzgNUt/EgRkcRJOg0hYdnA24hejmv\nlRy4t6gtIuRhDMXsBURXW1uc8bIq80SXs4m53uQ/kB4o7j3RxAP1wdwTlHNTdPKz\n3UgRus/hdtAoWk3QXMYV1NNdOVaznmEa1aeT6oEpzaNCHtCQCnLvdx0yqaByymjH\nfNo2OjGcwMYSGsilqF93cofSpA/qpETyDdtsZ17qjsMCggEBAMOwwq2I0Z+ZObmm\nvpOilyijb6AkM96P+WT+BdR/3GYjCv2TibUqqsdmmtYK05g3+TfaadEoF4bOp4nf\nfD5yoOWcTUfbNHec0HFB4j9Pvq3Dh3Rgoosoe829cDCq2khhhPEE0YRRtNnplxcN\naKmCxureNolcmO2CVeGSv8dbR+Dkz8pynjMSQvjFSWv5Tf9BDBVG1V+Gl4W+iAzs\nVhBzirCrH7a8yn+qohwF0m0nIU3VtL4SHekuu6Gga7oL2SWUBbcXFjmXxNTH3yY0\nIOe04nKbtmx9mLs799vulWg95SIEy4e9W67KTzfDYBKKLtc3akcTrKUJEr+Ks6BD\nkgCCPmUCggEAA6wdu6iTZFUR1Gd+pApb2D0JdtOnZNi9ezgfaynwKLHouxpnohS/\nCBW51RZI6TIJoKa5fVGhtw8zO6VZm5TdrZf3f21xBdQ2IdqFXO26Pbuxg99QhT6l\nOTF+EhCk9VhGom8kvFcuJEyF265wJq3muhqGDfXCXfE/ohOYguAaW4kBNA/3NtZH\nlOvkgf55t76YytGzSfRbPe4iD0r42VoSzexuwKYMTORn5XCNKbleXAGKy/0+zt4w\nTw3bLx0X6kvBzhnjMAKVwZPnoXNWkfpWYTJdv6IgCfTYSarkELjTjRZ8gDwUiWzD\n4H+74UKZm7kkMgjOm1SKkHhMsij/KxlCcQKCAQAAlis36VlPsQZdUfwKBF2s8jp6\ny/AY3Yp8ZLziOidG13DQTi8ch7flJYgQPU/CkBs3n7Efcd+yZC6tJGZykZpvzQf1\nrAjcu7cDiuciKEXFVrmQbPSzn8FCfWo6zEBm+KphvXFdcrX5CIrDhLunM6O/SYhh\nYhS4ejFDrKzhNHWU2VaHl4DJMxEHpWynvl23wGKfyJLx7+NOGVbCAPRrOamCRo0p\nYV8I4/tdeR1TqzaA95R7cQ34Xp7Sohg9c0rS3r0awSExZpRTQpCDueIFzKci8jsQ\nQ+ooFG2EnQFyATI8yL2S4ArPWTT3Ank51xLoYVm91zZNl7m7S0e7pRSVWW4/\n-----END RSA PRIVATE KEY-----

     
     
     
     
     ## =========================================================
     ##              Management / Actuator
     ## =========================================================
     management.server.address=0.0.0.0
     management.server.port=8081
     #management.endpoints.web.base-path=/actuator
     #management.endpoints.enabled=true
     #management.endpoints.web.exposure.include=*
     #management.metrics.export.prometheus.enabled=true
     
     ## =========================================================
     ##              Hystrix
     ## =========================================================
     #hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=5000
     #hystrix.command.default.circuitBreaker.requestVolumeThreshold=5
     #hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds=10000
     #hystrix.command.default.circuitBreaker.errorThresholdPercentage=50
     
     ## =========================================================
     ##              Zipkin
     ## =========================================================
     #spring.zipkin.base-url=http://zipkin:9411/
     #spring.sleuth.sampler.probability=1
     
     ## =========================================================
     ##              VPH Database
     ## =========================================================
     #spring.jpa.hibernate.ddl-auto=none
     #spring.datasource.url=jdbc:mysql://vph-mysql:3306/vph
     #spring.datasource.username=vph
     #spring.datasource.password=vph
     
     ## =========================================================
     ##              SFTP
     ## =========================================================
     #iamp.sftp.server=sierra-fs.westus2.cloudapp.azure.com
     #iamp.sftp.port=22
     #iamp.sftp.user=dwolfe
     #iamp.sftp.password=k7C!5KNg$p1umf
     #iamp.sftp.privateKey=
     #iamp.sftp.privateKeyPassphrase=
     #iamp.sftp.local.directory=/sftp/
     #iamp.sftp.remote.directory=/home/dwolfe/
     
     #log4j.category.com.jcraft.jsch=DEBUG
     
     ## =========================================================
     ##              Endpoints
     ## =========================================================
     #endpoint.vph=http://rsi-vph:8080
     #endpoint.icbc.adapter=http://rsi-icbc-adapter:8080
     #endpoint.icbc=http://rsi-icbc:8080/icbc/v1/ws/createContravention
        
     ## =========================================================
     ##              Logging
     ## =========================================================
     logging.config=config/logback.xml
     #logging.path=logs
     logging.level.root=INFO
     
     ## =========================================================
     ##              JMX
     ## =========================================================
     #spring.jmx.enabled=false
     
    logback.xml: |-
     <?xml version="1.0" encoding="UTF-8"?>
     <!DOCTYPE xml>
     <configuration scan="true" scanPeriod="30 seconds" >
         <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
             <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
         </appender>
         <root level="info">
             <appender-ref ref="STDOUT" />
         </root>
     </configuration>
     
    bootstrap.properties: |-
     spring.cloud.config.uri = http://config-server-v1-1-0-0-snapshot:8080/config-server/v1