apiVersion: v1
kind: Template
labels:
  template: service-autoscaler-cpu
metadata:
  annotations:
    description: Service Auto Scale based on CPU
  name: service-autoscaler-cpu
objects:
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  labels:
    app: ${APP_NAME}
  metadata:
    name: ${APP_NAME} 
  spec:
    scaleTargetRef:
      kind: DeploymentConfig 
      name: ${APP_NAME} 
      apiVersion: apps/v1
    minReplicas: ${{REPLICAS_MIN}}
    maxReplicas: ${{REPLICAS_MAX}}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: ${{CPU_THRESHOLD}}

parameters:
- description: The application name.
  displayName: Application Name
  name: APP_NAME
  value: app
- description: Minimum replicas.
  displayName: Minimum replicas
  name: REPLICAS_MIN
  value: "1"
- description: Maximun replicas.
  displayName: Maximum replicas
  name: REPLICAS_MAX
  value: "1"
- description: CPU threshold to replicate (%).
  displayName: CPU threshold to replicate (%)
  name: CPU_THRESHOLD
  value: "80"
